App\Entity\User:
  attributes:
    id:
      groups: ["user"]
    user_name:
      groups: ["user"]
    surname:
      groups: ["user"]
    user_email:
      groups: ["user"]
    password:
      groups: ["user"]
    user_phone:
      groups: ["user"]
    dni:
      groups: ["user"]
    active:
      groups: ["user"]
